### ISSUE TITLE
From Paul: Should this attribute be moved to "desirable"?

### ISSUE THREAD

**Issue by Greg4cr** [Greg4cr/sbse-sigsoft-standard#17]
- [ ] Multiple trials can either be performed as a cross-validation (multiple independent executions) or temporally (multiple applications as part of a timed sequence), depending on the problem at hand. 

Pauls believes this should shift to desirable as it "may not always apply". Do we agree?

**Comment by fedsar** [comment]
This sentence is a sub-item of  "One should sample from data multiple times in a controlled manner (where appropriate and possible)",  I think it might be considered as desirable and suggest that we move to desirable the whole attribute.
I would also suggest that we move to desirable "Compare results using statistics that compare distributions, rather than comparing the mean." since this is not always applicable.
